---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: default
spec:
  ports:
  - nodePort: 30003 # range is 30000-32768
    port: 3000 # port on the inside of the cluster
    targetPort: 3000 # target port inside container
  selector:
    app: sparta-app # this label to match service to deployment
  type: NodePort # expose the service via NodePort for external access of the cluster
