# YAML is case sensitive 
# use spaces not a tab
apiVersion: apps/v1 # specify api to use for deployment
kind: Deployment # kind of service/object you want to create
metadata:
  name: sparta-app-deployment # name the deployment
spec:
  selector:
    matchLabels:
      app: sparta-app  # look for this label/tab to match the k8 service
  # create a ReplicaSet with instances/pods
  replicas: 3
  template:
    metadata:
      labels:
        app: sparta-app
    spec:
      containers:
      - name: sparta-app
        image: priyansappal1/sparta-app:v1 # the image you created run mod nginx
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mongodb://mongo-service.default.svc.cluster.local:27017/posts" # (use just mongo-service)
        #command: ["/bin/sh", "-c"]
        #args: [cd .. && node seeds/seed.js && npm start]