---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: default
spec:
  selector:
    app: mongo
  ports:
    - nodePort: 30002 # - protocol: TCP (replace with this as it is more secure)
      port: 27017
      targetPort: 27017
  type: NodePort # can use ClusterIP (more secure - for internal access)