---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: default
spec:
  ports:
  - nodePort: 30003 # range is 30000-32768
    port: 3000
    targetPort: 3000
  selector:
    app: sparta-app # this label to match service to deployment
  type: NodePort
